preset: recommended

risky: true

linting: true

enabled:
  - strict
  - align_equals
  - newline_after_open_tag

disabled:
  - phpdoc_to_comment
  - unalign_equals
  - no_empty_phpdoc

finder:
  exclude:
    - "src/Model/*/*"
    - "src/Model/**/"
    - "src/Model/Channel/*"
    - "src/Model/Gateway/*"
    - "src/Model/Guild/*"
    - "src/Model/Invite/*"
    - "src/Model/Permissions/*"
    - "src/Model/User/*"
    - "src/Model/Voice/*"
    - "src/Model/Webhook/*"
    - "src/Interfaces/*"
